//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureDEGTYANNIKOVIN_3802
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fur_Specification_Materials
    {
        public int Id_Specification_Materials { get; set; }
        public int Id_Fr_Product { get; set; }
        public int Amount { get; set; }
        public int Id_Specficaton { get; set; }
    
        public virtual Fur_Product Fur_Product { get; set; }
        public virtual Specification Specification { get; set; }
    }
}
