//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureDEGTYANNIKOVIN_3802
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fur_Operation_Specification
    {
        public int Id_Operation_Specification { get; set; }
        public string Number_Operation { get; set; }
        public string Name_Operation { get; set; }
        public System.TimeSpan Time_On_Operation { get; set; }
        public int Id_Type_Equipment { get; set; }
        public int Id_Specficaton { get; set; }
    
        public virtual Fur_Type_Equipment Fur_Type_Equipment { get; set; }
        public virtual Specification Specification { get; set; }
    }
}
