//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureDEGTYANNIKOVIN_3802
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fur_Furniture
    {
        public int Id_Fur_Furniture { get; set; }
        public string Article { get; set; }
        public string Unit_Of_Measurement { get; set; }
        public int Amount { get; set; }
        public int Id_Provider { get; set; }
        public byte[] Image { get; set; }
        public int Id_Type_Furniture { get; set; }
        public double Cost { get; set; }
        public double Weight { get; set; }
    
        public virtual Fr_Type_Furniture Fr_Type_Furniture { get; set; }
        public virtual Fur_Provider Fur_Provider { get; set; }
    }
}
