//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureDEGTYANNIKOVIN_3802
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fur_Material
    {
        public int Id_Fur_Material { get; set; }
        public string Article { get; set; }
        public string Amount { get; set; }
        public int Id_Provider { get; set; }
        public byte[] Image { get; set; }
        public int Id_Fur_Type_Material { get; set; }
        public Nullable<double> Cost { get; set; }
        public string State_Standart { get; set; }
        public Nullable<double> Length { get; set; }
        public string Description { get; set; }
        public Nullable<int> Id_Fur_Material_Unit_Of_Measurement { get; set; }
    
        public virtual Fur_Material_Unit_Of_Measurement Fur_Material_Unit_Of_Measurement { get; set; }
        public virtual Fur_Provider Fur_Provider { get; set; }
        public virtual Fur_Type_Materal Fur_Type_Materal { get; set; }
    }
}
