//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureDEGTYANNIKOVIN_3802
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fur_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fur_Order()
        {
            this.Fur_Manager = new HashSet<Fur_Manager>();
        }
    
        public int Id_Fr_Order { get; set; }
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public int Id_Fr_Product { get; set; }
        public int Id_Fr_User { get; set; }
        public int Id_Fr_Manager { get; set; }
        public int Cost { get; set; }
        public System.DateTime End_Date { get; set; }
        public byte[] scheme { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fur_Manager> Fur_Manager { get; set; }
        public virtual Fur_Product Fur_Product { get; set; }
        public virtual Fur_User Fur_User { get; set; }
    }
}
